trigger:
- master  # Triggers on pushes to the master branch

pool:
  vmImage: 'windows-latest'  # Uses Microsoft-hosted agent (or switch to self-hosted if needed)

stages:
# 🚀 BUILD STAGE
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - script: echo "🚀 Build Stage Started"
    - script: echo "Hello from Build Stage! ✅"
    - script: echo "Build Completed Successfully"

# 📦 RELEASE STAGE
- stage: Release
  displayName: 'Release Stage'
  dependsOn: Build  # Runs after Build stage
  jobs:
  - job: ReleaseJob
    displayName: 'Release Job'
    steps:
    - script: echo "📦 Release Stage Started"
    - script: echo "Hello from Release Stage! 🎉"
    - script: echo "Release Completed Successfully"
